<?php
/**
 * @var \DistriMedia\Connector\Model\Config\Frontend\StartStockSync $block
 */
?>
<script>
    require(['prototype'], function(){
        function StartStockSync() {
            var validationMessage = $('validation_result');

            new Ajax.Request('<?= $block->escapeUrl($block->getAjaxUrl()) ?>', {
                onSuccess: function(response) {
                    var result = '<?= $block->escapeHtml(__('Error while scheduling a new Full Import.')); ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.valid === 1) {
                            validationMessage.removeClassName('hidden').addClassName('success')
                        } else {
                            validationMessage.removeClassName('hidden').addClassName('error')
                        }
                    } catch (e) {
                        validationMessage.removeClassName('hidden').addClassName('error')
                    }
                    validationMessage.update(result);
                }
            });
        }

        window.startStockSync = StartStockSync;
    });
</script>
<div class="actions">
    <button onclick="javascript:startStockSync(); return false;"
            type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p><?= $block->escapeHtml(__("Status: ") . " " . $block->getStatus()); ?></p>
    <p><?= $block->escapeHtml(__("Last Executed: ") . " " . $block->getLastExecutionDate()); ?></p>
    <div id="validation_result" class="message-validation hidden"></div>
</div>
